### ISSUE TITLE
[Feat] Android app to support BLE OBD2 devices

### ISSUE THREAD

**Issue by Chaoscontrol** [developerfromjokela/nissan-leaf-tcu#2]
I have been trying to connect to my OBD2, which is BLE, so it doesn't pair with the phone. 

But the TCU app won't find it at all. I've tried several times. The OBD2 is a LeLink2. It works perfect with Leafspy, as it supports BLE, but not with this app. 

It's the only step left I have to do for the set up. :(

**Comment by developerfromjokela** [comment]
> Eventually OCW itself will be able to Write TCU config. But not doable yet. :( Supporting BLE devices seems like an easier fix for now I think. 

I'll try to implement it today :)

**Comment by FreeTheExpo67** [comment]
I'm having exactly the same issue. I wonder if there's another way to update the APN

**Comment by Chaoscontrol** [comment]
Eventually OCW itself will be able to Write TCU config. But not doable yet. :( Supporting BLE devices seems like an easier fix for now I think.

**Comment by FreeTheExpo67** [comment]
> I'll try to implement it today :)

Looking forward to it!

**Comment by developerfromjokela** [comment]
Damn this got lost amongst other things, sorry. One day turned in to weeks :(  I have half-ass implementation of BLE but can't test, dont have the adapter myself. I'll clean it up and make a test version. Someone wants to test on my behalf?

**Comment by Chaoscontrol** [comment]
Yeah, I'll happily test it.

**Comment by developerfromjokela** [comment]
https://github.com/developerfromjokela/nissan-leaf-tcu/blob/ble/configapp-android/app/release/tcu-configurator-1.0.1-beta.apk please test here @Chaoscontrol and others

**Comment by FreeTheExpo67** [comment]
Unfortunately that update doesn't seem to work. I see a new button marked BLE but pressing that takes me to the same screen as the connect button and my LELink2 doesn't show up even when I press the scan button

**Comment by developerfromjokela** [comment]
> Unfortunately that update doesn't seem to work. I see a new button marked BLE but pressing that takes me to the same screen as the connect button and my LELink2 doesn't show up even when I press the scan button

Is it paired?

**Comment by FreeTheExpo67** [comment]
No it's not paired, if we were able to pair then the main version would work. My understanding is that pairing is just for classic BT while BTLE has to be implemented in the device or app. On LeafSpy, for example, connecting is just a case of selecting the BLE option when connecting

**Comment by developerfromjokela** [comment]
ok interesting. I'll dig in more. There's also leafspy support coming at some point, not sure when. but the developer said he will add it.

**Comment by developerfromjokela** [comment]
@FreeTheExpo67 here is update, added BLE device scanner: https://github.com/developerfromjokela/nissan-leaf-tcu/blob/ble/configapp-android/app/release/tcu-configurator-1.0.2-beta.apk

Hopefully the UUID is correct for LELink and it will connect by clicking on it :)

**Comment by FreeTheExpo67** [comment]
> [@FreeTheExpo67](https://github.com/FreeTheExpo67) here is update, added BLE device scanner: https://github.com/developerfromjokela/nissan-leaf-tcu/blob/ble/configapp-android/app/release/tcu-configurator-1.0.2-beta.apk
> 
> Hopefully the UUID is correct for LELink and it will connect by clicking on it :)

Unfortunately it didn't work. I got it to scan but no devices are found and I tried multiple times. I have the LELink2 so if you added support for LELink (i,e version 1) then perhaps that's the issue here

**Comment by developerfromjokela** [comment]
I searched LELINK2, found its uuid somewhere. what about this version , I added location permission that you can try giving it in the app info. https://github.com/developerfromjokela/nissan-leaf-tcu/blob/ble/configapp-android/app/release/tcu-configurator-1.0.4-beta.apk (sorry for releasing updates so quickly 😆 )

**Comment by developerfromjokela** [comment]
On my phone devices started started showing up after allowing location :) even though android docs say it should with without 🤣

**Comment by developerfromjokela** [comment]
oops I think I left one more bug preventing from connecting. quick patch coming

**Comment by developerfromjokela** [comment]
https://github.com/developerfromjokela/nissan-leaf-tcu/blob/ble/configapp-android/app/release/tcu-configurator-1.0.5-beta.apk

**Comment by FreeTheExpo67** [comment]
No change with 1.0.5 other than a request for location permission

**Comment by developerfromjokela** [comment]
no devices? did you allow location permissions? it must be set to allow while in use and use precise location

**Comment by developerfromjokela** [comment]
which adapter did @Chaoscontrol have? maybe you have better luck? ;)

**Comment by Chaoscontrol** [comment]
Same one. LeLink2. Sorry I can't try atm, maybe later today.

**Comment by Chaoscontrol** [comment]
I can search for BLE devices. It finds plenty. I tap the one I think it is (OBDBLE name, though I'm not 100% sure). And then it gets this error. Tried multiple times. 

<img width="1080" height="2392" alt="Image" src="https://github.com/user-attachments/assets/74b915ec-b642-43ab-ba93-f22b775878cc" />

**Comment by developerfromjokela** [comment]
> I can search for BLE devices. It finds plenty. I tap the one I think it is (OBDBLE name, though I'm not 100% sure). And then it gets this error. Tried multiple times. 
> 
> <img width="1080" height="2392" alt="Image" src="https://github.com/user-attachments/assets/74b915ec-b642-43ab-ba93-f22b775878cc" />

Interesting.. are you sure it's the obd? If you know its mac address you can try figuring out. 

However if it's the case, could you try using an app like https://f-droid.org/packages/f.cking.software/ BLE radar to scan and send a screenshot of device details and its UUIDs?

**Comment by Chaoscontrol** [comment]
Here you go. I can't be certain of the MAC or UUID, because LeafSpy doesn't show it after connecting. I really think it's that, since this BLEScanner app shows it's very close with strong signal, and it disappears when I unplug it. 

<img width="300" height="2392" alt="Image" src="https://github.com/user-attachments/assets/a09bb9c8-e704-4171-b55e-b938cd0c3957" />

**Comment by developerfromjokela** [comment]
Haha there's one character difference in the UUID :) let me fix that and give it another try

**Comment by developerfromjokela** [comment]
https://github.com/developerfromjokela/nissan-leaf-tcu/blob/ble/configapp-android/app/release/tcu-configurator-1.0.6-beta.apk

**Comment by Chaoscontrol** [comment]
Same result. Same error.

**Comment by FreeTheExpo67** [comment]
I can confirm that it shows up as ODOBLE and I also get the same error.

I don't know if it's fixed but somehow the app didn't have location permission which is why I wasn't seeing any devices but now I get the same error as @Chaoscontrol

**Comment by developerfromjokela** [comment]
> I can confirm that it shows up as ODOBLE and I also get the same error.
> 
> I don't know if it's fixed but somehow the app didn't have location permission which is why I wasn't seeing any devices but now I get the same error as @Chaoscontrol 

Ok thanks for confirming. I'll see what I can do. It can't find the uuid even though it seems to be correct. I will add a dialog showing the uuids inside the app to debug further

**Comment by FreeTheExpo67** [comment]
I'm happy to test but maybe I should ask whether it's worth putting effort into this given that updating the Nav does the same thing (and more). The only people who benefit are those with a BLE OBD2 device and without a way to write an image to an SD card

**Comment by developerfromjokela** [comment]
> I'm happy to test but maybe I should ask whether it's worth putting effort into this given that updating the Nav does the same thing (and more). The only people who benefit are those with a BLE OBD2 device and without a way to write an image to an SD card 

Yeah, it would be nice to have it. I'll order lelink2 and test it here. Much more easier to debug :D

And there's also upcoming support in leafspy, we'll see.

**Comment by Chaoscontrol** [comment]
> I'm happy to test but maybe I should ask whether it's worth putting effort into this given that updating the Nav does the same thing (and more). The only people who benefit are those with a BLE OBD2 device and without a way to write an image to an SD card

I was seeking confirmation for this too, as I was able to fully (I think) use OCW without ever updating the TCU APN or URL. Just by updating the Navi, everything seems to work. 

We were discussing that here a while ago: https://github.com/developerfromjokela/opencarwings/discussions/3

**Comment by developerfromjokela** [comment]
Yes seems like it's working without it, but TCU supports same level of configuration as obd but over the network. I'll do more work on reverse engineering that bit so we can reconfigure APN from the server.

Let's say the TCU restarts or you disconnect 12v, it will default to the settings defined in TCU memory. So you'll have to turn on the navi again for it to change to correct APN. 

This method via navi only also restricts user to one server, which is the public instance I am hosting. You could first set it up on public instance and move it to your own if you wish.

**Comment by Chaoscontrol** [comment]
> This method via navi only also restricts user to one server, which is the public instance I am hosting. You could first set it up on public instance and move it to your own if you wish.

Why is that? When configuring via Navi you can also set the server URL, right? 

Tbh I've been having issues with this when testing my Home Assistant addon instance. I currently have my private connection selected in the navi, but my server commands don't work yet (might be for different reasons) AND the public instance commands still work (which I find very strange).

**Comment by Chaoscontrol** [comment]
I still haven't been able to get OCW working again ever since I messed with the APN and URLs. I switched to a new SIM today, changed APNs, and still nothing. It can connect to public server from the car, it receives the SMS, but it doesn't respond to commands (timeouts). 

I don't know why it worked before, but it seems I will need the TCU updated to get it working. Is there any update on the BLE support? I can do further testing if needed.

**Comment by developerfromjokela** [comment]
> I still haven't been able to get OCW working again ever since I messed with the APN and URLs. I switched to a new SIM today, changed APNs, and still nothing. It can connect to public server from the car, it receives the SMS, but it doesn't respond to commands (timeouts). 
> 
> I don't know why it worked before, but it seems I will need the TCU updated to get it working. Is there any update on the BLE support? I can do further testing if needed.

I pushed update today which brings notifications when ids mismatch

**Comment by Chaoscontrol** [comment]
I did the tests today after the update, and I just got the same timeouts. 

<img width="1140" height="436" alt="Image" src="https://github.com/user-attachments/assets/ebe032c9-27c3-4804-b129-9b9b34f13f8b" />

Not sure what's the case you mean about ids mismatching. It might not be the same issue.

**Comment by developerfromjokela** [comment]
In this case the tcu fails to reach the server completely. There are scenarios where sim id or tcu id do not match and resulted in timeout before the update. Now it shows an error

**Comment by developerfromjokela** [comment]
Try doing a hard reset by either pulling tcu fuse or 12v battery disconnect. I have had these weird timeouts occur on aze0 from time to time.

**Comment by Chaoscontrol** [comment]
> Try doing a hard reset by either pulling tcu fuse or 12v battery disconnect. I have had these weird timeouts occur on aze0 from time to time.

I tried today disconnecting the 12V battery. I don't know what that's supposed to do. It reset some settings in the dashboard, but nothing in the navigator. The connections and all settings were still there, and it was still the same (navigator connecting and updating stations, but car not responding to commands). 

Then I also tried disconnecting all cables from the TCU with the car off. Then plugged it back in. No change either. It took some time for it to reconnect to the server (it was saying communications were busy), but same result. Navigator connects, but no response from commands. 

Is there anything else I can try? Are you too far from fixing the BLE? 

Otherwise my only other option is to buy another OBD2 just to read/write to the TCU and see if that's the issue really.

**Comment by developerfromjokela** [comment]
> > Try doing a hard reset by either pulling tcu fuse or 12v battery disconnect. I have had these weird timeouts occur on aze0 from time to time.
> 
> I tried today disconnecting the 12V battery. I don't know what that's supposed to do. It reset some settings in the dashboard, but nothing in the navigator. The connections and all settings were still there, and it was still the same (navigator connecting and updating stations, but car not responding to commands). 
> 
> Then I also tried disconnecting all cables from the TCU with the car off. Then plugged it back in. No change either. It took some time for it to reconnect to the server (it was saying communications were busy), but same result. Navigator connects, but no response from commands. 
> 
> Is there anything else I can try? Are you too far from fixing the BLE? 
> 
> Otherwise my only other option is to buy another OBD2 just to read/write to the TCU and see if that's the issue really. 

I haven't received my ble obd yet, go ahead and buy the normal bluetooth obd. Don't know when I'll get it :)

**Comment by Chaoscontrol** [comment]
I received my OBDII, it's this cheap one. 

<img width="300" height="458" alt="Image" src="https://github.com/user-attachments/assets/d5028863-a746-4662-b582-99ae5e7edd98" />

It connected fine, it showed "Telematics connection succesful" on screen. 

But then I tap "Read" on any of the fields, and I get this same error message: `For input string: "UN" unders raidx 16`. Nothing else shows. 

<img width="300" height="2392" alt="Image" src="https://github.com/user-attachments/assets/278f40ea-fcf4-492e-a568-9c06d2ac0665" />

Any idea what's the problem?

Edit: I think it's this OBDII adapter issue. I tried 4 different apps and none can connect to the car. Some can connect to the adapter, but all report the adapter can't talk to the car. When trying my BLE adapter, they connect fine. So it's not a car issue. Just a cheap OBD2 adapter. 

Edit 2: to avoid polluting this issue, I'll move my questions related to this to this other discussion https://github.com/developerfromjokela/opencarwings/discussions/10

**Comment by Mvb1122** [comment]
Hey, anyone else still having this issue? I'm using the last 1.0.6-beta.apk uploaded here, and getting the no serial profile error :( 

If it's relevant, I'm using an LeLink adapter, and I have _not_ yet swapped the SIM out, as I'm waiting for it to arrive. I just figured I might as well do the parameter changing since I had spare time.
